version: '3.8'

services:
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env.dev
    depends_on:
      - postgres_db

  postgres_db:
      image: postgres:14-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=movies
        - POSTGRES_PASSWORD=movies
        - POSTGRES_DB=movies_dev

volumes:
  postgres_data:







